In [1]:
!python --version

Python 3.13.9

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd

Series

In [4]:
t=(10,11,12)
d=pd.Series(t)
d

0    10
1    11
2    12
dtype: int64

In [5]:
type(t)

tuple

In [6]:
type(d)

pandas.core.series.Series

In [7]:
l1=[45,78,56,445,78]
d=pd.Series(l1)
d

0     45
1     78
2     56
3    445
4     78
dtype: int64

In [8]:
type(l1)

list

In [9]:
type(d)

pandas.core.series.Series

In [10]:
d={'a':1,'b':2,'c':3,'d':4}
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [11]:
d.keys()

dict_keys(['a', 'b', 'c', 'd'])

In [12]:
d['c']

3

In [13]:
b=pd.Series(d)
b

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
import numpy as np

In [15]:
l1=list(range(12))
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [16]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
d=pd.Series(np.arange(20))
d[5:15:2]

5      5
7      7
9      9
11    11
13    13
dtype: int64

In [18]:
a=pd.Series(list(range(20+1)))
a[2:5]

2    2
3    3
4    4
dtype: int64

Dataframe

In [20]:
data=[['abc',1],['def',2],['hij'],['klm',5],[6,"vj]"]]
type(data)

list

In [21]:
a=pd.DataFrame(data)
a

     0     1
0  abc     1
1  def     2
2  hij  None
3  klm     5
4    6   vj]

In [23]:
d=pd.DataFrame(data,columns=['name','marks'],index=['A','B','C','D','E'])
d

  name marks
A  abc     1
B  def     2
C  hij  None
D  klm     5
E    6   vj]

In [24]:
d1={"name":["vijay","raju","raj"],"age":[25,26,27]}
d1.keys()

dict_keys(['name', 'age'])

In [25]:
d1.values()

dict_values([['vijay', 'raju', 'raj'], [25, 26, 27]])

In [26]:
d2=pd.DataFrame(d1)
d2

    name  age
0  vijay   25
1   raju   26
2    raj   27

In [27]:
data={'name':['a','b','c','d','e','f'],'age':[45,12,48,25,12,56]}
data.keys()

dict_keys(['name', 'age'])

In [28]:
d=pd.DataFrame(data)
d

  name  age
0    a   45
1    b   12
2    c   48
3    d   25
4    e   12
5    f   56

In [30]:
d.columns=['Candidate','Age_in_years']
d

  Candidate  Age_in_years
0         a            45
1         b            12
2         c            48
3         d            25
4         e            12
5         f            56

In [32]:
d.rename({2:"num1"},axis=0,inplace=True)
d

     Candidate  Age_in_years
0            a            45
1            b            12
num1         c            48
3            d            25
4            e            12
5            f            56

In [33]:
d.rename({'Age_in_years':"Age"},axis=1,inplace=True)
d

     Candidate  Age
0            a   45
1            b   12
num1         c   48
3            d   25
4            e   12
5            f   56